services:
       event_manager:
        class: cooFood\EventBundle\Service\EventService
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage", "@form.factory"]
       user_event_manager:
        class: cooFood\EventBundle\Service\UserEventService
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage", "@form.factory"]
       order_manager:
        class: cooFood\EventBundle\Service\OrderService
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
       payfororder:
        class: cooFood\EventBundle\Service\PayForOrderService
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]