coo_food_event:
    resource: "@cooFoodEventBundle/Controller/"
    type:     annotation
    prefix:   /

coo_food_supplier:
    resource: "@cooFoodSupplierBundle/Controller/"
    type:     annotation
    prefix:   /

coo_food_user:
    resource: "@cooFoodUserBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

howto:
    path: /howto
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    'Static/howto.html.twig'