<?php

namespace cooFood\eventBundle\Entity;

/**
 * eventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class eventRepository extends \Doctrine\ORM\EntityRepository
{
}
