<?php

namespace cooFood\eventBundle\Entity;

/**
 * eventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class eventRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByNot($field, $value)
    {
        $qb = $this->createQueryBuilder('builder');
        $qb->where($qb->expr()->not($qb->expr()->eq('builder.'.$field, '?1')));
        $qb->setParameter(1, $value);

        return $qb->getQuery()
            ->getResult();
    }
}
